config/routes.rb
Tutor::Application.routes.draw do

  get "chat/:room", to: "chat#nickname"
  get "chat/:room/:nickname", to: "chat#index"
  post "chat/:room/:nickname", to: "chat#write"
  get "chat/:room/:nickname/refresh/:lastid", to: "chat#refresh"

  resources :exams

  resources :rooms

  resources :analyses

  get  "tutorial", to: "tutorial#index"
  post "tutorial/assess", to: "tutorial#assess"
  get  "tutorial/search", to: "tutorial#search"
  post "tutorial/move", to: "tutorial#move"
  post "tutorial/create_student", to: "tutorial#create_student"
  post "tutorial/settings", to: "tutorial#settings"
  post "tutorial/email", to: "tutorial#email"

  get  "about", to: "about#index"
  get  "analyses/:id/execute", to: "analyses#execute"

  get  "status", to: "status#new"
  post "status/create", to: "status#create"
  get  "status/show/:token", to: "status#show"
  get  "status/schedule", to: "status#schedule"
  get  "schedule", to: "status#schedule"

  get  "load", to: "load#index"
  post "load/tumonline", to: "load#tumonline"
  post "load/tutoren", to: "load#tutoren"

  get "users/:id/magiclogin/:magictoken", to: "users#magiclogin"
  get "users/:id/reset", to: "users#reset"
  get "users/:id/associate", to: "users#associate"

  post "exams/:id/assign_seats", to: "exams#assign_seats"
  post "exams/:id/reset_seats", to: "exams#reset_seats"
  get "exams/:id/print_roomdoor", to: "exams#print_roomdoor"
  get "exams/:id/print_signatures", to: "exams#print_signatures"
  get "exams/:id/export_seats", to: "exams#export_seats"
  get "exams/:id/export_grades", to: "exams#export_grades"
  get "exams/:id/grade/:magictoken", to: "exams#grade"
  post "exams/:id/grade/:magictoken", to: "exams#grade_save"
  get "exams/:id/score", to: "exams#score"
  post "exams/:id/score", to: "exams#apply_score"

  devise_for :users

  resources :weeks
  resources :assessments
  resources :groups
  resources :courses
  resources :students
  resources :users

  root 'tutorial#index'

  

end

app/models/week.rb
class Week < ActiveRecord::Base
	belongs_to :course
	has_many :assessments

	def select_name
		start.strftime("Week of %b %d")
	end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admincheck
  before_action :set_week, only: [:show, :edit, :update, :destroy]

  # GET /weeks
  # GET /weeks.json
  def index
    @weeks = @course.weeks
  end

  # GET /weeks/new
  def new
    @week = Week.new
  end

  # GET /weeks/1/edit
  def edit
  end

  # POST /weeks
  # POST /weeks.jso 
 def create
    @week = Week.new(week_params.merge(course_id: @course.id))
    if @week.save
      redirect_to '/weeks'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /weeks/1
  # PATCH/PUT /weeks/1.json
  def update
    if @week.update(week_params)
      redirect_to '/weeks'
    else
      render action: 'edit'
    end
  end

  # DELETE /weeks/1
  # DELETE /weeks/1.json
  def destroy
    @week.destroy
    redirect_to '/weeks'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_week
      @week = Week.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def week_params
      params.require(:week).permit(:start,:course_id)
    end
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/weeks/_form.html.haml
= form_for @week do |f|
  - if @week.errors.any?
    #error_explanation
      %h2= "#{pluralize(@week.errors.count, "error")} prohibited this week from being saved:"
      %ul
        - @week.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :course
    = @course.name
  .form-group.form-inline
    = f.label :start
    = f.date_select :start, {}, { :class => "form-control" }
  .actions
    = f.submit 'Save', :class => "btn btn-primary"

app/views/weeks/edit.html.haml
%h1 Editing week

= render 'form'

= link_to 'Show', @week
\|
= link_to 'Back', weeks_path

app/views/weeks/index.html.haml
%h1 Listing weeks for course #{@course.name}

%table.table.table-striped
  %thead
    %tr
      %th Course
      %th Start
      %th
      %th

  %tbody
    - @weeks.each do |week|
      %tr
        %td= week.course ? week.course.name : "unassigned"
        %td= week.start.strftime("%a, %d.%m.%Y")
        %td= link_to 'Edit', edit_week_path(week)
        %td= link_to 'Destroy', week, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Week', new_week_path

app/views/weeks/new.html.haml
%h1 New week

= render 'form'