config/routes.rb
Tutor::Application.routes.draw do

  get "chat/:room", to: "chat#nickname"
  get "chat/:room/:nickname", to: "chat#index"
  post "chat/:room/:nickname", to: "chat#write"
  get "chat/:room/:nickname/refresh/:lastid", to: "chat#refresh"

  resources :exams

  resources :rooms

  resources :analyses

  get  "tutorial", to: "tutorial#index"
  post "tutorial/assess", to: "tutorial#assess"
  get  "tutorial/search", to: "tutorial#search"
  post "tutorial/move", to: "tutorial#move"
  post "tutorial/create_student", to: "tutorial#create_student"
  post "tutorial/settings", to: "tutorial#settings"
  post "tutorial/email", to: "tutorial#email"

  get  "about", to: "about#index"
  get  "analyses/:id/execute", to: "analyses#execute"

  get  "status", to: "status#new"
  post "status/create", to: "status#create"
  get  "status/show/:token", to: "status#show"
  get  "status/schedule", to: "status#schedule"
  get  "schedule", to: "status#schedule"

  get  "load", to: "load#index"
  post "load/tumonline", to: "load#tumonline"
  post "load/tutoren", to: "load#tutoren"

  get "users/:id/magiclogin/:magictoken", to: "users#magiclogin"
  get "users/:id/reset", to: "users#reset"
  get "users/:id/associate", to: "users#associate"

  post "exams/:id/assign_seats", to: "exams#assign_seats"
  post "exams/:id/reset_seats", to: "exams#reset_seats"
  get "exams/:id/print_roomdoor", to: "exams#print_roomdoor"
  get "exams/:id/print_signatures", to: "exams#print_signatures"
  get "exams/:id/export_seats", to: "exams#export_seats"
  get "exams/:id/export_grades", to: "exams#export_grades"
  get "exams/:id/grade/:magictoken", to: "exams#grade"
  post "exams/:id/grade/:magictoken", to: "exams#grade_save"
  get "exams/:id/score", to: "exams#score"
  post "exams/:id/score", to: "exams#apply_score"

  devise_for :users

  resources :weeks
  resources :assessments
  resources :groups
  resources :courses
  resources :students
  resources :users

  root 'tutorial#index'

  

end

app/models/exam.rb
require 'csv'    

class Exam < ActiveRecord::Base
	belongs_to :course

	has_and_belongs_to_many :rooms
	accepts_nested_attributes_for :rooms

	has_many :exam_tasks
  	accepts_nested_attributes_for :exam_tasks, reject_if: :all_blank, allow_destroy: true

	has_many :exam_seats
	has_and_belongs_to_many :students

	has_many :exam_assessments
	
	has_many :exam_grades


	def seats?
		exam_seats.length > 0
	end

	def graded?
		students.length == exam_grades.length
	end

	def roominfo
		nil if not seats?
		rooms.order(:name).map do |room|
			students = exam_seats.includes(:student).where("room_id = ? and student_id is not null", room.id)
					.to_a.sort_by { |seat|  ActiveSupport::Inflector.transliterate(seat.student.name) }
					.map { |seat| seat.student }
			{
				name: room.name,
				count: exam_seats.where(:room_id => room.id).count,
				first: ActiveSupport::Inflector.transliterate(students.first.name),
				last: ActiveSupport::Inflector.transliterate(students.last.name),
			}
		end
	end

	def prefix_length(a,b)
		minl = [a.length,b.length].min
		(0..minl-1).each do |i|
			return i if (a[i]!=b[i]) 
		end
		return minl
	end

	def roominfo_public
		info = roominfo
		last = nil
		clean = []
		info.each_with_index do |i,index|
			if last.nil? then
				i[:first] = "A"
			else
				l = prefix_length(i[:first], last[:last])
				last[:last] = last[:last][0,l+1]
				i[:first] = i[:first][0,l+1]
			end

			if index == info.length-1
				i[:last] = "Z"
			end 

			clean << i
			last=i
		end
		clean
	end

	def original_import=(v)
		write_attribute(:original_import, File.read(v.path, :encoding => 'iso-8859-15'))

		self.start=nil
		self.students = []
		CSV.open(v.path, { 
			:encoding => 'iso-8859-15', 
			:headers => true,
			:col_sep => ';' 
		}).each do |row|
			self.start = DateTime.parse(row["DATE_OF_ASSESSMENT"]) 
			s = Student.find_or_create_by_matrnr(row["REGISTRATION_NUMBER"].to_i)
			s.update_attributes({ :lastname => row["FAMILY_NAME_OF_STUDENT"], :firstname => row["FIRST_NAME_OF_STUDENT"] })
			self.students << s
		end
	end

	def export(filename)
		# open original import
		orig = CSV.new(original_import, { 
			headers: true,
			col_sep: ';' 
		})

		# build something alike for output
		first=true
		CSV.open(filename, "w", 
			:encoding => 'iso-8859-15', 
			:headers => false,
			:write_headers => false,
			:col_sep => ';',
			:force_quotes => true
		) do |csv|
			orig.each do |p|
				if first then
					csv << p.to_hash.keys
					first=false
				end
				data = yield p["REGISTRATION_NUMBER"].to_i
				p["GRADE"] = data[0].to_s
				p["REMARK"] = data[1].to_s
				csv << p
			end
		end
	end

	def export_seats(filename)
		export(filename) do |matrnr|
			["", exam_seats.includes(:student).where("students.matrnr" => matrnr).first.seat_string]
		end
	end

	def export_grades(filename)
		export(filename) do |matrnr|
			g = exam_grades.includes(:student).where("students.matrnr" => matrnr).first
			[g.grade ? g.grade : "x" , g.remark]
		end
	end
end

app/controllers/exams_controller.rb
require 'awesome_print'
require 'prawn'
require 'tempfile'
require 'digest/sha1'

class ExamsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:grade_save]
  before_filter :authenticate_user!, except: [:grade, :grade_save]
  before_filter :admincheck, except: [:grade, :grade_save]
  before_filter :magiccheck, only: [:grade, :grade_save]
  before_action :set_exam, only: [:show, :edit, :update, :destroy, :assign_seats, :reset_seats, :print_roomdoor, :print_signatures, :export_seats, :export_grades, :grade, :grade_save]

  def magiccheck
    render_403 unless Exam.where(id: params[:id], magictoken: params[:magictoken]).present?
  end

  # GET /exams
  # GET /exams.json
  def index
    @exams = @course.exams
    @other_exams = Exam.where('id not in (?)', @exams.map{ |e| e.id }.to_a + [ -1 ])
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new({course: @course})
  end

  # GET /exams/1/edit
  def edit
  end

  def grade
    if params["letter"]
      l = params["letter"]
      return render json: @exam.students.to_a.select { |student| fix(student.lastname)[0] == l }
        .map { |student| student.serializable_hash.select { |k,v| ["matrnr","lastname","firstname","id"].include?(k) } }
        .map { |student| 
          ea = ExamAssessment.where(student_id: student["id"], exam: @exam).first
          student.merge({
            matrnr: "xxxx" + student["matrnr"].to_s[-4,4], 
            assessment_string: ea.present? ? ea.assessment_string : ""
          }) 
        }
    end

    if params["check"]
      a = ExamAssessment.new({ exam: @exam, assessment_string: params["check"] })
      a.valid?
      render :json => a.errors[:exam_task_assessments].to_a
    end
  end

  def grade_save
    ActiveRecord::Base.transaction do
      params["points"].each do |id,str|
        ExamAssessment.where(exam_id: @exam.id, student_id: id).destroy_all
        ExamAssessment.create({
          exam: @exam,
          student: Student.find(id),
          assessment_string: str
        })
      end
    end
    redirect_to :action => :grade, :magictoken => params[:magictoken]
  end

  def extract_seat(s)
    seat = s.gsub(/^.*Reihe /, "").gsub("Platz ",":").split(":")
    seat.map do |v| 
      if v.strip.match(/^[0-9]+$/)
        v.strip.to_i
      else
        v.strip
      end
    end
  end

  def export_seats
    file="/tmp/export-seats-#{Time.now.to_i}.csv"
    @exam.export_seats(file)
    send_file file, :type => "application/force-download", :disposition => "attachment"
  end

  def export_grades
    raise "implement me"
    file="/tmp/export-grades-#{Time.now.to_i}.csv"
    @exam.export(file)
    send_file file, :type => "text/csv", :disposition => "attachment"
  end

  def print_signatures
    file="/tmp/signatures-#{Time.now.to_i}.pdf"
    Prawn::Document.generate(file, :page_layout => :landscape) do |pdf|
      @exam.rooms.order(:name).each_with_index do |room,index|
        pdf.start_new_page if index!=0

        # header
        pdf.formatted_text [{ text: "Unterschriften #{@exam.name} - #{room.name}", styles: [:bold], size: 27 }]
        pdf.move_down 15

        t = [["<b>MatrNr</b>", "<b>Lastname</b>", "<b>Firstname</b>", "<b>Row</b>", "<b>Seat</b>", "<b>Unterschrift</b>"]]
        t+= @exam.exam_seats.includes(:student).where(room_id: room).to_a.sort_by { |a| 
          a.split 
        }.map do |seat|
          if not seat.student.present?
            [ "<font size='7'><sup>reserve</sup></font>", "", "", seat.row, seat.seat, "" ]
          else
            [ 
              seat.student.matrnr,
              seat.student.lastname,
              seat.student.firstname,
              seat.row,
              seat.seat,
              ""
            ]
          end
        end

        pdf.table t, { 
          :header => true,
          :row_colors =>["FFFFFF","eeeeee"], 
          :width => pdf.bounds.width, 
          :cell_style =>{:inline_format => true }, 
          :column_widths => {5 => 250}
        }
      end

      pdf.number_pages "<page>/<total>", {:at => [0, -3],:size => 7}
    end
    send_file file, :type => "application/pdf", :disposition => "attachment"
  end

  def print_roomdoor
    file="/tmp/roomdoor-#{Time.now.to_i}.pdf"
    Prawn::Document.generate(file) do |pdf|
      @exam.rooms.order(:name).each_with_index do |room,index|
        pdf.start_new_page if index!=0

        # header
        pdf.formatted_text [{ text: "Aushang #{@exam.name} - #{room.name}", styles: [:bold], size: 27 }]
        pdf.move_down 15

        # table
        t = [["<b>Lastname</b>", "<b>Firstname</b>", "<b>Seat</b>"]]
        t+= @exam.exam_seats.includes(:student).where(["room_id = ? and student_id is not null",room.id]).sort { |a,b| 
          [fix(a.student.lastname),fix(a.student.firstname)]<=>[fix(b.student.lastname),fix(b.student.firstname)]
        }.map do |seat|
          [ seat.student.lastname,seat.student.firstname,seat.seat_string]
        end
        pdf.table t, header: true,:row_colors =>["FFFFFF","eeeeee"], :width => pdf.bounds.width, :cell_style =>{:inline_format => true }
      end

      pdf.number_pages "<page>/<total>", {:at => [0, -3],:size => 7}
    end
    send_file file, :type => "application/pdf", :disposition => "attachment"
  end

  def fix(s)
    ActiveSupport::Inflector.transliterate(s)
  end

  def assign_seats
    return redirect_to @exam, notice: "You must reset the seat assignment before calling assign again" if @exam.exam_seats.length > 0

    ActiveRecord::Base.transaction do
      # Determine available and required seats
      rooms = @exam.rooms.order(:name)
      roomCounts = rooms.map { |r| r.seat_count }
      total = roomCounts.inject(0) { |sum, r| sum + r }
      leftover = total - @exam.students.size
      return redirect_to @exam, notice: "You have insufficient rooms, you need #{-leftover} more seats." if leftover < 0

      # Convervatively even out on rooms
      roomCounts.map! { |r| (r * (1-(leftover/total.to_f))).ceil }

      # Reduce largest room until exact count is reached
      while roomCounts.reduce(:+) > @exam.students.size
        roomCounts[roomCounts.each_with_index.max[1]] -= 1
      end

      # Split students
      last = 0
      roomStudents = rooms.map { [] }
      currentRoom=0
      students = @exam.students.sort { |a,b| [fix(a.lastname),fix(a.firstname)]<=>[fix(b.lastname),fix(b.firstname)] }
      students.each do |s|
        roomStudents[currentRoom] << s
        currentRoom+=1 if (roomStudents[currentRoom].length >= roomCounts[currentRoom])
      end

      # Map seats
      rooms.each_with_index.map do |room,index|
        random_seats = room.seats.split(/\r?\n/).shuffle
        roomStudents[index].each_with_index do |student,i| 
          @exam.exam_seats << ExamSeat.create({ student: student, room: room, seat_string: random_seats[i] })
        end
        for i in (roomStudents[index].length..random_seats.length-1)
          @exam.exam_seats << ExamSeat.create({ room: room, seat_string: random_seats[i] })
        end
      end
      @exam.save
    end

    redirect_to @exam
  end

  def reset_seats
    @exam.exam_seats.delete_all
    @exam.save
    redirect_to @exam, notice: "Seat assignment successfully reset."
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render action: 'show', status: :created, location: @exam }
      else
        format.html { render action: 'new' }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:name, :start, :course_id, :original_import, :magictoken, { :room_ids => [] }, :exam_tasks_attributes => [:id, :number, :name, :max_points, :_destroy] )
    end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_exam_task_fields.html.haml
.nested-fields
  .form-group
    .col-sm-2
      = f.text_field :number, :placeholder => "No.", :class => "form-control"
    .col-sm-2
      = f.text_field :max_points, :placeholder => "Max Points", :class => "form-control"
    .col-sm-6
      = f.text_field :name, :placeholder => "Name", :class => "form-control"
    .col-sm-2
      = link_to_remove_association "remove", f, :class => "btn btn-danger"

app/views/exams/_form.html.haml
= form_for @exam do |f|
  - if @exam.errors.any?
    #error_explanation
      %h2= "#{pluralize(@exam.errors.count, "error")} prohibited this exam from being saved:"
      %ul
        - @exam.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :course_id
    = f.collection_select :course_id, Course.all, :id, :name, {}, { class: 'form-control' }
  .form-group
    = f.label :name
    = f.text_field :name, :class => "form-control"
  .form-group
    = f.label :magictoken
    %a(onclick="$('#exam_magictoken').val(Math.random().toString(36).slice(2)+Math.random().toString(36).slice(2));") (generate random token)
    = f.text_field :magictoken, :class => "form-control"
  .form-group
    = f.label :original_import, "TUMonline CSV for Exam"
    = f.file_field :original_import 
    - #= f.text_area :original_import, :class => "form-control", :rows => 15
  .form-group
    = f.label :exam_tasks
    #exam_tasks.form-horizontal(style="padding-left:10px")
      = f.fields_for :exam_tasks do |t|
        = render 'exam_task_fields', :f => t
      .links
        = link_to_add_association 'add task', f, :exam_tasks, :class => "btn btn-success"
  .form-group
    = f.label :rooms
    = hidden_field_tag 'exam[room_ids][]', nil
    %div(style="padding-left: 10px")
      - Room.all.each do |r|
        .checkbox
          %label
            = check_box_tag 'exam[room_ids][]', r.id, @exam.room_ids.include?(r.id)
            = r.name
  .actions
    = f.submit 'Save'

app/views/exams/_index_table.html.haml
%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Start
      %th Participants
      %th Rooms
      %th Seats
      %th Grades
      %th
      %th
      %th
      %th
      %th

  %tbody
    - exams.each do |exam|
      %tr
        %td= exam.name
        %td= exam.start.strftime("%d.%m.%y")
        %td= exam.students.length
        %td= exam.rooms.length
        %td 
          - if exam.seats?
            %i.glyphicon.glyphicon-ok.text-success
          - else
            %i.glyphicon.glyphicon-remove.text-danger
        %td 
          - if exam.graded?
            %i.glyphicon.glyphicon-ok.text-success
          - else
            %i.glyphicon.glyphicon-remove.text-danger
        %td= link_to 'Seats', exam
        %td= link_to 'Point Entry', { action: :grade, magictoken: exam.magictoken, :id => exam }
        %td= link_to 'Grades', { :action => "score", :id => exam }
        %td= link_to 'Edit', edit_exam_path(exam)
        %td= link_to 'Destroy', exam, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/exams/edit.html.haml
%h1 Editing exam

= render 'form'

= link_to 'Show', @exam
\|
= link_to 'Back', exams_path

app/views/exams/grade.html.haml
%h1 
	Grading #{@exam.name}, #{@exam.start.strftime("%d.%m.%y")}
	= link_to '(edit)', edit_exam_path(@exam)

%p.alert.alert-danger#notice
	Select a letter to add grades for. FIRST get the exams, THEN select the letter. Exams act as a mutual exclusion, this system does not.

%div
	%b Students total: 
	= @exam.students.count
	&nbsp;
	%b Students with points:
	= @exam.exam_assessments.where(:status => "attended").count
	&nbsp;
	%b Students noshow:
	= @exam.exam_assessments.where(:status => "noshow").count
	&nbsp;
	%b Students missing:
	= @exam.students.count - @exam.exam_assessments.count

%h2
	- ("A".."Z").each do |l|
		%a.letter{ :href => "#", "data-letter" => l }= l

= form_tag url_for(action: :grade, id: @exam), method: :post do
	%table.table.table-bordered.table-striped
		%thead
			%th Lastname
			%th Firstname
			%th MatrNr
			%th Grade Expression
			%th Status
		%tbody

	= submit_tag 'Save'

:coffeescript
	loadLetter = (l) ->
		$("#notice").hide()
		$.get '?letter='+l, (participants)->
			count = 0
			$("tbody tr").remove()
			for p in participants
				row = $("<tr/>")
				lastname = $("<td>").text(p.lastname); row.append(lastname)
				firstname = $("<td>").text(p.firstname); row.append(firstname)
				matrnr = $("<td>").text(p.matrnr); row.append(matrnr)
				expression = $('<td><input placeholder="a1+a2+a3..+a9" class="form-control" type="text" name="points['+p.id+']" value="'+p.assessment_string+'"/></td>'); 
				if !done && p.assessment_string.length == 0
					$(expression).find("input").attr("autofocus","autofocus") 
					done=true
				row.append(expression)
				if p.assessment_string.length == 0
					row.append('<td class="text-center"><i style="font-size:15pt" class="status glyphicon glyphicon-remove"></i></td>')
				else
					count += 1 if p.assessment_string? and p.assessment_string != "x"
					pts = ""
					pts = eval(p.assessment_string) if p.assessment_string? && p.assessment_string.indexOf('+') > 0
					row.append('<td class="text-center"><span><b>'+(pts)+'  </b></span><i style="font-size:15pt" class="status glyphicon glyphicon-ok"></i></td>')
				$("tbody").append(row)
			$("tbody").append($("<tr><td>"+count+"</td></tr>"))

			# XXX this should really use a view binding
			$("input").change (e)->
				$.get '?check='+encodeURIComponent($(e.target).val()), (res)=>
					icon = $(e.target).closest("td").next().find("i")
					icon.parent().find("span").remove()
					if res.length == 0
						icon.addClass("glyphicon-ok")
						icon.removeClass("glyphicon-remove")
						icon.addClass("text-success")
						icon.removeClass("text-danger")
						$(icon).tooltip({html: true, title:'looks good.'})
						icon.parent().prepend($("<span><b>"+(eval($(e.target).val()))+"  </b></span>"))
					else
						icon.removeClass("glyphicon-ok")
						icon.addClass("glyphicon-remove")
						icon.removeClass("text-success")
						icon.addClass("text-danger")
						icon.attr("alt",)
						$(icon).tooltip({html: true, title:res.join("<br/>")})



	$(".letter").click (e)->
		letter = $(e.target).attr("data-letter")
		loadLetter(letter)
		return false

app/views/exams/index.html.haml
%h1 Exams for #{@course.name}

= render partial: 'exams/index_table', locals: { exams: @exams }

%br

%h1 Other exams
= render partial: 'exams/index_table', locals: { exams: @other_exams }

%br

= link_to 'New Exam', new_exam_path

app/views/exams/new.html.haml
%h1 New exam

= render 'form'

= link_to 'Back', exams_path

app/views/exams/score.html.haml
.hidden-print.col-lg-4
	%h1 Map points to grades

	= form_tag({}, { method: :post }) do
		.form-group
			%textarea#score_method.rows(name="expr")= @exam.expr
		.form-group
			%button#run.btn.btn-danger Recalculate all grades and kill old grades (!)

		= link_to 'Export grades to TUMonline', { action: :export_grades, id: @exam }

.col-lg-8
	- Analysis.all.where(exam: true).each do |a|
		%h2= a.name
		%a.togglelink Show SQL Source
		%div.toggle
			%pre= a.query
		= render "analyses/analysis", :a => a

:coffeescript
	$(document).ready ->
		$('.toggle').hide()
	$('a.togglelink').click ->
		console.log "clicked"
		$('.toggle').hide()
		$(this).next('.toggle').toggle('slow')
		return false;

:coffeescript
	view=CodeMirror.fromTextArea $("#score_method")[0],
		mode: 'text/x-ruby'
		lineNumbers: true


	$("#run").click =>
		$.post window.location, { expr: view.getValue() }, (res) =>
			console.log res

app/views/exams/show.html.haml
%p#notice= notice

%h1 
	Exam #{@exam.name}, #{@exam.start.strftime("%d.%m.%y")}
	= link_to '(edit)', edit_exam_path(@exam), :class => "hidden-print"

.hidden-print
	%h2 Tasks
	%ul
		- @exam.exam_tasks.order(:number).each do |r|
			%li
				= r.number
				= r.name
				(#{r.max_points})


%h2 Rooms
- if @exam.seats?
	%table.table.table-striped
		%thead
			%tr
				%th Room
				%th # students
				%th From student (incl.)
				%th To student (incl.)
		%tbody
			- @exam.roominfo_public.each do |r|
				%tr
					%td= r[:name]
					%td= r[:count]
					%td= r[:first]
					%td= r[:last]
- else
	%ul
		- @exam.rooms.order(:name).each do |r|
			%li
				= r.name + "(" + @exam.exam_seats.where(:room_id => r.id).count.to_s + ")"

.hidden-print
	%h2 Seat Assignment
	- if @exam.seats?
		%ul
			%li= link_to 'Printout for room door', { action: :print_roomdoor }
			%li= link_to 'Printout for signatures', { action: :print_signatures }
			%li= link_to 'Export seats to TUMonline', { action: :export_seats }
		= button_to 'Reset seats', { action: :reset_seats }, :class => "btn btn-danger btn-xs", :data => { :confirm => 'Are you sure?' }
	- else
		= button_to 'Assign seats', { action: :assign_seats } , :class => "btn"